apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: play
  namespace: play
spec:
  releaseName: play-venus
  chart:
    git: https://github.com/aniedoziechris/gitopsplay.git
    path: charts/play
    ref: master
  values:
    image:
      repository: nginx
      tag: latest
    replicaCount: 1
