apiVersion: apps/v1
kind: Deployment
metadata:
  name: play
  namespace: play
spec:
  replicas: 1
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      namespace: play
      labels:
        app: play
    spec:
      containers:
      - name: play
        image: nginx
        ports:
        - containerPort: 80
          name: http
          
-------------------------------
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: play-ingress
  namespace: play
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /play
        backend:
          serviceName: play
          servicePort: 80
